import type { Metadata } from "next";
import "./globals.scss";
import { poppins } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={poppins.className} id="root">{children}</body>
    </html>
  );
}
